// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/study-room/Current.tsx": () => import("../components/mockups/study-room/Current.tsx"),
  "./components/mockups/study-room/Premium.tsx": () => import("../components/mockups/study-room/Premium.tsx")
};
